"""Add cascading deletes to tasks

Revision ID: 01fedec28392
Revises: 39528c694bba
Create Date: 2024-09-03 18:47:51.514825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01fedec28392'
down_revision = '39528c694bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_employee_id_employees', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_employee_id_employees'), 'employees', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_employee_id_employees'), type_='foreignkey')
        batch_op.create_foreign_key('fk_tasks_employee_id_employees', 'employees', ['employee_id'], ['id'])

    # ### end Alembic commands ###
