"""empty message

Revision ID: 602af6e44144
Revises: 911a6d082c88
Create Date: 2024-09-03 10:02:52.288578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '602af6e44144'
down_revision = '911a6d082c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_project',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_project_employee_id_employees')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_employee_project_project_id_projects')),
    sa.PrimaryKeyConstraint('employee_id', 'project_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_project')
    # ### end Alembic commands ###
